import { createRouter, createWebHashHistory } from 'vue-router'

export const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    { path: '/', redirect: '/workbench' },
    { path: '/login', component: () => import('../views/LoginPage.vue'), meta: { public: true } },
    { path: '/workbench', component: () => import('../views/WorkbenchPage.vue') },
    { path: '/documents', component: () => import('../views/DocumentCenterPage.vue') },
    { path: '/documents/:id', component: () => import('../views/DocumentDetailPage.vue'), props: true },
    { path: '/announcements', component: () => import('../views/AnnouncementPage.vue') },
    { path: '/announcements/:id', component: () => import('../views/AnnouncementDetailPage.vue') },
    { path: '/announcement-admin', component: () => import('../views/AnnouncementManagementPage.vue'), meta: { permission: 'ANNOUNCEMENT_MANAGE' } },
    { path: '/leave', component: () => import('../views/LeavePage.vue') },
    { path: '/leave/:id', component: () => import('../views/DetailPage.vue'), props: route => ({ module: 'leave', id: route.params.id }) },
    { path: '/expense', component: () => import('../views/ExpensePage.vue') },
    { path: '/expense/:id', component: () => import('../views/DetailPage.vue'), props: route => ({ module: 'expense', id: route.params.id }) },
    { path: '/travel', component: () => import('../views/TravelPage.vue') },
    { path: '/travel/:id', component: () => import('../views/TravelDetailPage.vue'), props: true },
    { path: '/purchase', component: () => import('../views/PurchasePage.vue') },
    { path: '/purchase/:id', component: () => import('../views/PurchaseDetailPage.vue'), props: true },
    { path: '/seal', component: () => import('../views/SealPage.vue') },
    { path: '/seal/:id', component: () => import('../views/SealDetailPage.vue'), props: true },
    { path: '/hr/employees', component: () => import('../views/PersonnelPage.vue') },
    { path: '/hr/employees/:id', component: () => import('../views/PersonnelDetailPage.vue'), props: true },
    { path: '/hr/personnel-cases', component: () => import('../views/PersonnelCasePage.vue') },
    { path: '/hr/personnel-cases/:id', component: () => import('../views/PersonnelCaseDetailPage.vue'), props: true },
    { path: '/hr/contracts', component: () => import('../views/ContractPage.vue') },
    { path: '/hr/contracts/:id', component: () => import('../views/ContractDetailPage.vue'), props: true },
    { path: '/attendance', component: () => import('../views/AttendancePage.vue') },
    { path: '/attendance/:id', component: () => import('../views/AttendanceDetailPage.vue'), props: true },
    { path: '/approval', component: () => import('../views/ApprovalPage.vue') },
    { path: '/approval/:id', component: () => import('../views/DetailPage.vue'), props: route => ({ module: 'notification', id: route.params.id }) },
    { path: '/calendar', component: () => import('../views/CalendarPage.vue') },
    { path: '/calendar/:id', component: () => import('../views/DetailPage.vue'), props: route => ({ module: 'calendar', id: route.params.id }) },
    { path: '/organization', component: () => import('../views/OrganizationPage.vue') },
    { path: '/users', component: () => import('../views/UserManagementPage.vue'), meta: { permission: 'USER_MANAGE' } },
    { path: '/security', component: () => import('../views/SecurityPage.vue') },
    { path: '/roles', component: () => import('../views/RoleManagementPage.vue'), meta: { permission: 'USER_MANAGE' } },
    { path: '/departments', component: () => import('../views/DepartmentManagementPage.vue'), meta: { permission: 'ORG_MANAGE' } },
    { path: '/positions', component: () => import('../views/PositionManagementPage.vue'), meta: { permission: 'ORG_MANAGE' } },
    { path: '/business-configurations', component: () => import('../views/BusinessConfigurationPage.vue'), meta: { permission: 'BUSINESS_CONFIG_MANAGE' } },
    { path: '/audit', component: () => import('../views/AuditPage.vue'), meta: { permission: 'AUDIT_VIEW' } },
    { path: '/processes', component: () => import('../views/ProcessPage.vue'), meta: { permission: 'PROCESS_MANAGE' } },
    { path: '/delegations', component: () => import('../views/DelegationPage.vue') },
    { path: '/copies', component: () => import('../views/CopyPage.vue') },
    { path: '/:pathMatch(.*)*', redirect: '/workbench' }
  ]
})
