using Microsoft.EntityFrameworkCore;
using Oa.Api.Domain;

namespace Oa.Api.Persistence;

public sealed class OaDbContext(DbContextOptions<OaDbContext> options) : DbContext(options)
{
    public DbSet<LeaveRecord> LeaveRequests => Set<LeaveRecord>();
    public DbSet<FlowTaskRecord> FlowTasks => Set<FlowTaskRecord>();
    public DbSet<LeaveBalanceRecord> LeaveBalances => Set<LeaveBalanceRecord>();
    public DbSet<ExpenseRecord> ExpenseClaims => Set<ExpenseRecord>();
    public DbSet<ExpenseItemRecord> ExpenseItems => Set<ExpenseItemRecord>();
    public DbSet<ExpenseTaskRecord> ExpenseTasks => Set<ExpenseTaskRecord>();
    public DbSet<TravelRecord> TravelRequests => Set<TravelRecord>();
    public DbSet<TravelTaskRecord> TravelTasks => Set<TravelTaskRecord>();
    public DbSet<PurchaseRequestRecord> PurchaseRequests => Set<PurchaseRequestRecord>();
    public DbSet<PurchaseTaskRecord> PurchaseTasks => Set<PurchaseTaskRecord>();
    public DbSet<PurchaseOrderRecord> PurchaseOrders => Set<PurchaseOrderRecord>();
    public DbSet<PurchaseReceiptRecord> PurchaseReceipts => Set<PurchaseReceiptRecord>();
    public DbSet<SealRequestRecord> SealRequests => Set<SealRequestRecord>();
    public DbSet<SealTaskRecord> SealTasks => Set<SealTaskRecord>();
    public DbSet<SealExecutionRecord> SealExecutions => Set<SealExecutionRecord>();
    public DbSet<SealReturnRecord> SealReturns => Set<SealReturnRecord>();
    public DbSet<PaymentRecordEntity> Payments => Set<PaymentRecordEntity>();
    public DbSet<AuditRecord> AuditLogs => Set<AuditRecord>();
    public DbSet<IdempotencyRecord> IdempotencyKeys => Set<IdempotencyRecord>();
    public DbSet<WorkCalendarRecord> WorkCalendarEntries => Set<WorkCalendarRecord>();
    public DbSet<NotificationRecord> Notifications => Set<NotificationRecord>();
    public DbSet<FileRecord> Files => Set<FileRecord>();
    public DbSet<ProcessDefinitionRecord> ProcessDefinitions => Set<ProcessDefinitionRecord>();
    public DbSet<ProcessRuleRecord> ProcessRules => Set<ProcessRuleRecord>();
    public DbSet<ProcessNodeRecord> ProcessNodes => Set<ProcessNodeRecord>();
    public DbSet<ProcessScopeRecord> ProcessScopes => Set<ProcessScopeRecord>();
    public DbSet<FlowDelegationRecord> FlowDelegations => Set<FlowDelegationRecord>();
    public DbSet<FlowInstanceRecord> FlowInstances => Set<FlowInstanceRecord>();
    public DbSet<FlowActionRecord> FlowActions => Set<FlowActionRecord>();
    public DbSet<FlowCopyRecipientRecord> FlowCopyRecipients => Set<FlowCopyRecipientRecord>();
    public DbSet<DepartmentRecord> Departments => Set<DepartmentRecord>();
    public DbSet<PositionRecord> Positions => Set<PositionRecord>();
    public DbSet<UserRecord> Users => Set<UserRecord>();
    public DbSet<UserAccountRecord> UserAccounts => Set<UserAccountRecord>();
    public DbSet<RoleRecord> Roles => Set<RoleRecord>();
    public DbSet<UserRoleRecord> UserRoles => Set<UserRoleRecord>();
    public DbSet<RolePermissionRecord> RolePermissions => Set<RolePermissionRecord>();
    public DbSet<RoleDataScopeRecord> RoleDataScopes => Set<RoleDataScopeRecord>();
    public DbSet<AuthSessionRecord> AuthSessions => Set<AuthSessionRecord>();
    public DbSet<MfaChallengeRecord> MfaChallenges => Set<MfaChallengeRecord>();
    public DbSet<AnnouncementRecord> Announcements => Set<AnnouncementRecord>();
    public DbSet<AnnouncementReadRecord> AnnouncementReads => Set<AnnouncementReadRecord>();
    public DbSet<PersonnelProfileRecord> PersonnelProfiles => Set<PersonnelProfileRecord>();
    public DbSet<PersonnelEventRecord> PersonnelEvents => Set<PersonnelEventRecord>();
    public DbSet<PersonnelCaseRecord> PersonnelCases => Set<PersonnelCaseRecord>();
    public DbSet<PersonnelCaseTaskRecord> PersonnelCaseTasks => Set<PersonnelCaseTaskRecord>();
    public DbSet<PersonnelCaseAlertDeliveryRecord> PersonnelCaseAlertDeliveries => Set<PersonnelCaseAlertDeliveryRecord>();
    public DbSet<AttendanceShiftRecord> AttendanceShifts => Set<AttendanceShiftRecord>();
    public DbSet<AttendanceRecordEntity> AttendanceRecords => Set<AttendanceRecordEntity>();
    public DbSet<AttendanceAppealRecord> AttendanceAppeals => Set<AttendanceAppealRecord>();
    public DbSet<AttendanceMonthLockRecord> AttendanceMonthLocks => Set<AttendanceMonthLockRecord>();
    public DbSet<AttendanceMonthSnapshotRecord> AttendanceMonthSnapshots => Set<AttendanceMonthSnapshotRecord>();
    public DbSet<EmploymentContractRecord> EmploymentContracts => Set<EmploymentContractRecord>();
    public DbSet<EmploymentContractEventRecord> EmploymentContractEvents => Set<EmploymentContractEventRecord>();
    public DbSet<ContractAlertAcknowledgementRecord> ContractAlertAcknowledgements => Set<ContractAlertAcknowledgementRecord>();
    public DbSet<ContractAlertDeliveryRecord> ContractAlertDeliveries => Set<ContractAlertDeliveryRecord>();
    public DbSet<DocumentCategoryRecord> DocumentCategories => Set<DocumentCategoryRecord>();
    public DbSet<KnowledgeDocumentRecord> KnowledgeDocuments => Set<KnowledgeDocumentRecord>();
    public DbSet<DocumentVersionRecord> DocumentVersions => Set<DocumentVersionRecord>();
    public DbSet<DocumentAcknowledgementRecord> DocumentAcknowledgements => Set<DocumentAcknowledgementRecord>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.Entity<LeaveRecord>(e => { e.ToTable("leave_request"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.Reason).HasMaxLength(500).IsRequired(); e.Property(x => x.Days).HasPrecision(6, 1); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.StartDate }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<FlowTaskRecord>(e => { e.ToTable("flow_task"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalAssigneeId).HasMaxLength(64); e.Property(x => x.OriginalAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.Sequence }); e.HasOne<LeaveRecord>().WithMany().HasForeignKey(x => x.LeaveRequestId).OnDelete(DeleteBehavior.Cascade); e.HasOne<FlowDelegationRecord>().WithMany().HasForeignKey(x => x.DelegationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<LeaveBalanceRecord>(e => { e.ToTable("leave_balance"); e.HasKey(x => x.Id); e.HasIndex(x => new { x.TenantId, x.UserId, x.LeaveType, x.Year }).IsUnique(); e.Property(x => x.StatutoryEntitled).HasPrecision(6, 1); e.Property(x => x.Adjustment).HasPrecision(6, 1); e.Property(x => x.Entitled).HasPrecision(6, 1); e.Property(x => x.Frozen).HasPrecision(6, 1); e.Property(x => x.Used).HasPrecision(6, 1); e.Property(x => x.Version).IsConcurrencyToken(); });
        b.Entity<ExpenseRecord>(e => { e.ToTable("expense_claim"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(64).IsRequired(); e.Property(x => x.PayeeAccountName).HasMaxLength(128).IsRequired(); e.Property(x => x.PayeeAccount).HasMaxLength(128).IsRequired(); e.Property(x => x.TotalAmount).HasPrecision(14, 2); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.CreatedAt }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); e.HasOne<TravelRecord>().WithMany().HasForeignKey(x => x.TravelRequestId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<ExpenseItemRecord>(e => { e.ToTable("expense_item"); e.HasKey(x => x.Id); e.Property(x => x.Category).HasMaxLength(32).IsRequired(); e.Property(x => x.Description).HasMaxLength(500).IsRequired(); e.Property(x => x.Amount).HasPrecision(14, 2); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.HasOne<ExpenseRecord>().WithMany().HasForeignKey(x => x.ExpenseClaimId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<ExpenseTaskRecord>(e => { e.ToTable("expense_task"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalAssigneeId).HasMaxLength(64); e.Property(x => x.OriginalAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.Sequence }); e.HasOne<ExpenseRecord>().WithMany().HasForeignKey(x => x.ExpenseClaimId).OnDelete(DeleteBehavior.Cascade); e.HasOne<FlowDelegationRecord>().WithMany().HasForeignKey(x => x.DelegationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<TravelRecord>(e => { e.ToTable("travel_request"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(64).IsRequired(); e.Property(x => x.Purpose).HasMaxLength(500).IsRequired(); e.Property(x => x.EstimatedBudget).HasPrecision(14, 2); e.Property(x => x.ItineraryJson).HasColumnType("jsonb"); e.Property(x => x.CompanionIdsJson).HasColumnType("jsonb"); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.StartDate }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<TravelTaskRecord>(e => { e.ToTable("travel_task"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalAssigneeId).HasMaxLength(64); e.Property(x => x.OriginalAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.Sequence }); e.HasOne<TravelRecord>().WithMany().HasForeignKey(x => x.TravelRequestId).OnDelete(DeleteBehavior.Cascade); e.HasOne<FlowDelegationRecord>().WithMany().HasForeignKey(x => x.DelegationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PurchaseRequestRecord>(e => { e.ToTable("purchase_request"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(100).IsRequired(); e.Property(x => x.Purpose).HasMaxLength(500).IsRequired(); e.Property(x => x.SuggestedSupplier).HasMaxLength(100); e.Property(x => x.ItemsJson).HasColumnType("jsonb"); e.Property(x => x.ItemSearchText).HasColumnType("text").IsRequired(); e.Property(x => x.EstimatedTotal).HasPrecision(16, 2); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.CreatedAt }); e.HasIndex(x => new { x.TenantId, x.RequiredDate, x.Status }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PurchaseTaskRecord>(e => { e.ToTable("purchase_task"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalAssigneeId).HasMaxLength(64); e.Property(x => x.OriginalAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.Property(x => x.Status).IsConcurrencyToken(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.Sequence }); e.HasOne<PurchaseRequestRecord>().WithMany().HasForeignKey(x => x.PurchaseRequestId).OnDelete(DeleteBehavior.Cascade); e.HasOne<FlowDelegationRecord>().WithMany().HasForeignKey(x => x.DelegationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PurchaseOrderRecord>(e => { e.ToTable("purchase_order"); e.HasKey(x => x.Id); e.HasIndex(x => x.PurchaseRequestId).IsUnique(); e.HasIndex(x => new { x.TenantId, x.OrderNumber }).IsUnique(); e.Property(x => x.Supplier).HasMaxLength(100).IsRequired(); e.Property(x => x.OrderNumber).HasMaxLength(64).IsRequired(); e.Property(x => x.ActualAmount).HasPrecision(16, 2); e.Property(x => x.Notes).HasMaxLength(500); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.HasOne<PurchaseRequestRecord>().WithOne().HasForeignKey<PurchaseOrderRecord>(x => x.PurchaseRequestId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<PurchaseReceiptRecord>(e => { e.ToTable("purchase_receipt"); e.HasKey(x => x.Id); e.HasIndex(x => x.PurchaseRequestId).IsUnique(); e.Property(x => x.Result).HasMaxLength(32).IsRequired(); e.Property(x => x.Notes).HasMaxLength(500).IsRequired(); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.HasOne<PurchaseRequestRecord>().WithOne().HasForeignKey<PurchaseReceiptRecord>(x => x.PurchaseRequestId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<SealRequestRecord>(e => { e.ToTable("seal_request"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(100).IsRequired(); e.Property(x => x.DocumentCategory).HasMaxLength(32).IsRequired(); e.Property(x => x.DocumentName).HasMaxLength(100).IsRequired(); e.Property(x => x.SealType).HasMaxLength(32).IsRequired(); e.Property(x => x.OutCustodian).HasMaxLength(64); e.Property(x => x.Reason).HasMaxLength(500).IsRequired(); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.CreatedAt }); e.HasIndex(x => new { x.TenantId, x.Status, x.CreatedAt }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<SealTaskRecord>(e => { e.ToTable("seal_task"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalAssigneeId).HasMaxLength(64); e.Property(x => x.OriginalAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.Property(x => x.Status).IsConcurrencyToken(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.Sequence }); e.HasOne<SealRequestRecord>().WithMany().HasForeignKey(x => x.SealRequestId).OnDelete(DeleteBehavior.Cascade); e.HasOne<FlowDelegationRecord>().WithMany().HasForeignKey(x => x.DelegationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<SealExecutionRecord>(e => { e.ToTable("seal_execution"); e.HasKey(x => x.Id); e.HasIndex(x => x.SealRequestId).IsUnique(); e.Property(x => x.OperatorName).HasMaxLength(64).IsRequired(); e.Property(x => x.Notes).HasMaxLength(500); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.HasOne<SealRequestRecord>().WithOne().HasForeignKey<SealExecutionRecord>(x => x.SealRequestId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<SealReturnRecord>(e => { e.ToTable("seal_return"); e.HasKey(x => x.Id); e.HasIndex(x => x.SealRequestId).IsUnique(); e.Property(x => x.SealCondition).HasMaxLength(32).IsRequired(); e.Property(x => x.ReceiverName).HasMaxLength(64).IsRequired(); e.Property(x => x.Notes).HasMaxLength(500); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.HasOne<SealRequestRecord>().WithOne().HasForeignKey<SealReturnRecord>(x => x.SealRequestId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<DocumentCategoryRecord>(e => { e.ToTable("document_category"); e.HasKey(x => x.Id); e.Property(x => x.Code).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(100).IsRequired(); e.Property(x => x.Description).HasMaxLength(500); e.Property(x => x.DepartmentId).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.Code }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.SortOrder }); });
        b.Entity<KnowledgeDocumentRecord>(e => { e.ToTable("knowledge_document"); e.HasKey(x => x.Id); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.Property(x => x.Title).HasMaxLength(100).IsRequired(); e.Property(x => x.Summary).HasMaxLength(500).IsRequired(); e.Property(x => x.Content).HasColumnType("text").IsRequired(); e.Property(x => x.TagsJson).HasColumnType("text"); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.DepartmentId).HasMaxLength(64); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.PublishedBy).HasMaxLength(64); e.Property(x => x.PublishedByName).HasMaxLength(64); e.Property(x => x.ArchivedBy).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.CategoryId, x.Status }); e.HasIndex(x => new { x.TenantId, x.Status, x.EffectiveDate }); e.HasOne<DocumentCategoryRecord>().WithMany().HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<DocumentVersionRecord>(e => { e.ToTable("document_version"); e.HasKey(x => x.Id); e.Property(x => x.Title).HasMaxLength(100).IsRequired(); e.Property(x => x.Summary).HasMaxLength(500).IsRequired(); e.Property(x => x.Content).HasColumnType("text").IsRequired(); e.Property(x => x.ChangeNotes).HasMaxLength(500); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.PublishedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.PublishedByName).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.TenantId, x.DocumentId, x.Version }).IsUnique(); e.HasOne<KnowledgeDocumentRecord>().WithMany().HasForeignKey(x => x.DocumentId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<DocumentAcknowledgementRecord>(e => { e.ToTable("document_acknowledgement"); e.HasKey(x => x.Id); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.UserName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentId).HasMaxLength(64); e.Property(x => x.DepartmentName).HasMaxLength(64); e.Property(x => x.ClientIp).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.DocumentId, x.DocumentVersion, x.UserId }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.UserId, x.AcknowledgedAt }); e.HasOne<KnowledgeDocumentRecord>().WithMany().HasForeignKey(x => x.DocumentId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<PaymentRecordEntity>(e => { e.ToTable("payment_record"); e.HasKey(x => x.Id); e.HasIndex(x => x.ExpenseClaimId).IsUnique(); e.Property(x => x.PaymentMethod).HasMaxLength(32).IsRequired(); e.Property(x => x.TransactionNumber).HasMaxLength(128).IsRequired(); e.Property(x => x.ProofFile).HasMaxLength(512).IsRequired(); e.Property(x => x.OperatorId).HasMaxLength(64).IsRequired(); e.Property(x => x.PaidAmount).HasPrecision(14, 2); e.HasOne<ExpenseRecord>().WithMany().HasForeignKey(x => x.ExpenseClaimId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<AuditRecord>(e => { e.ToTable("audit_log"); e.HasKey(x => x.Id); e.Property(x => x.ActorId).HasMaxLength(64).IsRequired(); e.Property(x => x.Action).HasMaxLength(64).IsRequired(); e.Property(x => x.ResourceType).HasMaxLength(64).IsRequired(); e.Property(x => x.ResourceId).HasMaxLength(64).IsRequired(); e.Property(x => x.Summary).HasMaxLength(500).IsRequired(); e.HasIndex(x => new { x.TenantId, x.ResourceType, x.ResourceId, x.OccurredAt }); });
        b.Entity<IdempotencyRecord>(e => { e.ToTable("idempotency_key"); e.HasKey(x => x.Id); e.Property(x => x.ActorId).HasMaxLength(64).IsRequired(); e.Property(x => x.Route).HasMaxLength(256).IsRequired(); e.Property(x => x.Key).HasMaxLength(128).IsRequired(); e.Property(x => x.RequestHash).HasMaxLength(64); e.Property(x => x.ResponseJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.TenantId, x.ActorId, x.Route, x.Key }).IsUnique(); });
        b.Entity<WorkCalendarRecord>(e => { e.ToTable("work_calendar"); e.HasKey(x => x.Id); e.Property(x => x.Note).HasMaxLength(200); e.HasIndex(x => new { x.TenantId, x.Date }).IsUnique(); });
        b.Entity<NotificationRecord>(e => { e.ToTable("notification"); e.HasKey(x => x.Id); e.Property(x => x.RecipientId).HasMaxLength(64).IsRequired(); e.Property(x => x.Type).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(200).IsRequired(); e.Property(x => x.Content).HasMaxLength(500).IsRequired(); e.Property(x => x.ResourceType).HasMaxLength(64).IsRequired(); e.Property(x => x.ResourceId).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.TenantId, x.RecipientId, x.ReadAt, x.CreatedAt }); });
        b.Entity<FileRecord>(e => { e.ToTable("file_object"); e.HasKey(x => x.Id); e.Property(x => x.OwnerId).HasMaxLength(64).IsRequired(); e.Property(x => x.OriginalName).HasMaxLength(255).IsRequired(); e.Property(x => x.StoredName).HasMaxLength(128).IsRequired(); e.Property(x => x.ContentType).HasMaxLength(100).IsRequired(); e.HasIndex(x => new { x.TenantId, x.OwnerId, x.CreatedAt }); });
        b.Entity<ProcessDefinitionRecord>(e => { e.ToTable("process_definition"); e.HasKey(x => x.Id); e.Property(x => x.Code).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(100).IsRequired(); e.Property(x => x.BusinessType).HasMaxLength(32).IsRequired(); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.PublishedBy).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.Code, x.Version }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.BusinessType, x.Status }); });
        b.Entity<ProcessRuleRecord>(e => { e.ToTable("process_rule"); e.HasKey(x => x.Id); e.Property(x => x.MaxValue).HasPrecision(14, 2); e.HasIndex(x => new { x.ProcessDefinitionId, x.Sequence }).IsUnique(); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<ProcessNodeRecord>(e => { e.ToTable("process_node"); e.HasKey(x => x.Id); e.Property(x => x.AssigneeKey).HasMaxLength(128).IsRequired(); e.HasIndex(x => new { x.ProcessRuleId, x.Sequence }).IsUnique(); e.HasOne<ProcessRuleRecord>().WithMany().HasForeignKey(x => x.ProcessRuleId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<ProcessScopeRecord>(e => { e.ToTable("process_scope"); e.HasKey(x => x.Id); e.Property(x => x.ScopeType).HasMaxLength(32).IsRequired(); e.Property(x => x.Value).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.ProcessDefinitionId, x.ScopeType, x.Value }).IsUnique(); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<FlowDelegationRecord>(e => { e.ToTable("flow_delegation"); e.HasKey(x => x.Id); e.Property(x => x.OwnerId).HasMaxLength(64).IsRequired(); e.Property(x => x.DelegateId).HasMaxLength(64).IsRequired(); e.Property(x => x.BusinessType).HasMaxLength(32).IsRequired(); e.Property(x => x.Reason).HasMaxLength(200).IsRequired(); e.HasIndex(x => new { x.TenantId, x.OwnerId, x.Status, x.StartAt, x.EndAt }); });
        b.Entity<FlowInstanceRecord>(e => { e.ToTable("flow_instance"); e.HasKey(x => x.Id); e.Property(x => x.BusinessType).HasMaxLength(32).IsRequired(); e.Property(x => x.BusinessNumber).HasMaxLength(32).IsRequired(); e.Property(x => x.ApplicantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ProcessDefinitionCode).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.TenantId, x.BusinessType, x.BusinessId, x.Attempt }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.ApplicantId, x.Status, x.StartedAt }); e.HasOne<ProcessDefinitionRecord>().WithMany().HasForeignKey(x => x.ProcessDefinitionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<FlowActionRecord>(e => { e.ToTable("flow_action"); e.HasKey(x => x.Id); e.Property(x => x.ActorId).HasMaxLength(64).IsRequired(); e.Property(x => x.ActorName).HasMaxLength(64).IsRequired(); e.Property(x => x.FromAssigneeId).HasMaxLength(64); e.Property(x => x.FromAssigneeName).HasMaxLength(64); e.Property(x => x.ToAssigneeId).HasMaxLength(64); e.Property(x => x.ToAssigneeName).HasMaxLength(64); e.Property(x => x.Comment).HasMaxLength(500); e.HasIndex(x => new { x.FlowInstanceId, x.OccurredAt }); e.HasOne<FlowInstanceRecord>().WithMany().HasForeignKey(x => x.FlowInstanceId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<FlowCopyRecipientRecord>(e => { e.ToTable("flow_copy_recipient"); e.HasKey(x => x.Id); e.Property(x => x.BusinessType).HasMaxLength(32).IsRequired(); e.Property(x => x.BusinessNumber).HasMaxLength(32).IsRequired(); e.Property(x => x.ApplicantName).HasMaxLength(64).IsRequired(); e.Property(x => x.RecipientId).HasMaxLength(64).IsRequired(); e.Property(x => x.RecipientName).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(200).IsRequired(); e.Property(x => x.Status).HasMaxLength(32); e.HasIndex(x => new { x.TenantId, x.BusinessType, x.BusinessId, x.RecipientId }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.RecipientId, x.ReadAt, x.AvailableAt }); });
        b.Entity<DepartmentRecord>(e => { e.ToTable("department"); e.HasKey(x => x.Id); e.Property(x => x.Id).HasMaxLength(64); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(100).IsRequired(); e.Property(x => x.ParentId).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.Name }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.ParentId, x.SortOrder, x.Name }); e.HasOne<DepartmentRecord>().WithMany().HasForeignKey(x => x.ParentId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PositionRecord>(e => { e.ToTable("position"); e.HasKey(x => x.Id); e.Property(x => x.Id).HasMaxLength(64); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(100).IsRequired(); e.Property(x => x.DepartmentId).HasMaxLength(64).IsRequired(); e.Property(x => x.Status).HasMaxLength(16).IsRequired(); e.HasIndex(x => new { x.TenantId, x.DepartmentId, x.Name }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.DepartmentId, x.Status, x.SortOrder, x.Name }); e.HasOne<DepartmentRecord>().WithMany().HasForeignKey(x => x.DepartmentId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<UserRecord>(e => { e.ToTable("oa_user"); e.HasKey(x => x.Id); e.Property(x => x.Id).HasMaxLength(64); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentId).HasMaxLength(64).IsRequired(); e.Property(x => x.PositionId).HasMaxLength(64); e.Property(x => x.ManagerId).HasMaxLength(64); e.Property(x => x.Status).HasMaxLength(16).IsRequired(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.DepartmentId, x.Status, x.Name }); e.HasOne<PositionRecord>().WithMany().HasForeignKey(x => x.PositionId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<UserAccountRecord>(e => { e.ToTable("user_account"); e.HasKey(x => x.UserId); e.Property(x => x.UserId).HasMaxLength(64); e.Property(x => x.PasswordSalt).HasMaxLength(128).IsRequired(); e.Property(x => x.PasswordHash).HasMaxLength(128).IsRequired(); e.Property(x => x.MfaSecretCiphertext).HasMaxLength(512); e.Property(x => x.RecoveryCodeHashesJson).HasColumnType("jsonb").HasDefaultValue("[]"); e.HasOne<UserRecord>().WithOne().HasForeignKey<UserAccountRecord>(x => x.UserId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<RoleRecord>(e => { e.ToTable("security_role"); e.HasKey(x => x.Code); e.Property(x => x.Code).HasMaxLength(64); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Name).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Name }).IsUnique(); });
        b.Entity<UserRoleRecord>(e => { e.ToTable("user_role"); e.HasKey(x => new { x.UserId, x.RoleCode }); e.Property(x => x.UserId).HasMaxLength(64); e.Property(x => x.RoleCode).HasMaxLength(64); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade); e.HasOne<RoleRecord>().WithMany().HasForeignKey(x => x.RoleCode).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<RolePermissionRecord>(e => { e.ToTable("role_permission"); e.HasKey(x => new { x.RoleCode, x.PermissionCode }); e.Property(x => x.RoleCode).HasMaxLength(64); e.Property(x => x.PermissionCode).HasMaxLength(64); e.HasOne<RoleRecord>().WithMany().HasForeignKey(x => x.RoleCode).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<RoleDataScopeRecord>(e => { e.ToTable("role_data_scope"); e.HasKey(x => new { x.RoleCode, x.ResourceType }); e.Property(x => x.RoleCode).HasMaxLength(64); e.Property(x => x.ResourceType).HasMaxLength(32); e.Property(x => x.Scope).HasMaxLength(32).IsRequired(); e.HasOne<RoleRecord>().WithMany().HasForeignKey(x => x.RoleCode).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<AuthSessionRecord>(e => { e.ToTable("auth_session"); e.HasKey(x => x.Id); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.RefreshTokenHash).HasMaxLength(64).IsRequired(); e.Property(x => x.UserAgent).HasMaxLength(256); e.Property(x => x.IpAddress).HasMaxLength(64); e.Property(x => x.RevokedReason).HasMaxLength(64); e.HasIndex(x => x.RefreshTokenHash).IsUnique(); e.HasIndex(x => new { x.UserId, x.RevokedAt, x.ExpiresAt }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<MfaChallengeRecord>(e => { e.ToTable("mfa_challenge"); e.HasKey(x => x.Id); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.TokenHash).HasMaxLength(64).IsRequired(); e.Property(x => x.Purpose).HasMaxLength(16).IsRequired(); e.Property(x => x.PendingSecretCiphertext).HasMaxLength(512); e.Property(x => x.UserAgent).HasMaxLength(256); e.Property(x => x.IpAddress).HasMaxLength(64); e.HasIndex(x => x.TokenHash).IsUnique(); e.HasIndex(x => new { x.UserId, x.ConsumedAt, x.ExpiresAt }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<AnnouncementRecord>(e => { e.ToTable("announcement"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(200).IsRequired(); e.Property(x => x.Content).HasMaxLength(10000).IsRequired(); e.Property(x => x.Status).HasMaxLength(16).IsRequired(); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.PublishedBy).HasMaxLength(64); e.Property(x => x.WithdrawnBy).HasMaxLength(64); e.HasIndex(x => new { x.TenantId, x.Status, x.PublishedAt }); });
        b.Entity<AnnouncementReadRecord>(e => { e.ToTable("announcement_read"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.AnnouncementId, x.UserId }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.UserId, x.ReadAt }); e.HasOne<AnnouncementRecord>().WithMany().HasForeignKey(x => x.AnnouncementId).OnDelete(DeleteBehavior.Cascade); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<PersonnelProfileRecord>(e => { e.ToTable("personnel_profile"); e.HasKey(x => x.UserId); e.Property(x => x.UserId).HasMaxLength(64); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.EmployeeNumber).HasMaxLength(32).IsRequired(); e.Property(x => x.WorkEmail).HasMaxLength(128).IsRequired(); e.Property(x => x.WorkPhone).HasMaxLength(32).IsRequired(); e.Property(x => x.WorkLocation).HasMaxLength(100).IsRequired(); e.Property(x => x.EmploymentType).HasMaxLength(32).IsRequired(); e.Property(x => x.PersonnelStatus).HasMaxLength(32).IsRequired(); e.Property(x => x.DepartureReason).HasMaxLength(500); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.EmployeeNumber }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.PersonnelStatus, x.HireDate }); e.HasOne<UserRecord>().WithOne().HasForeignKey<PersonnelProfileRecord>(x => x.UserId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PersonnelEventRecord>(e => { e.ToTable("personnel_event"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.EventType).HasMaxLength(32).IsRequired(); e.Property(x => x.Summary).HasMaxLength(500).IsRequired(); e.Property(x => x.ChangedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.ChangedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.SnapshotJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.TenantId, x.UserId, x.EffectiveDate, x.CreatedAt }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PersonnelCaseRecord>(e => { e.ToTable("personnel_case"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Number).HasMaxLength(32).IsRequired(); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.EmployeeName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(100).IsRequired(); e.Property(x => x.Type).HasMaxLength(32).IsRequired(); e.Property(x => x.Title).HasMaxLength(200).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.Property(x => x.OwnerId).HasMaxLength(64).IsRequired(); e.Property(x => x.OwnerName).HasMaxLength(64).IsRequired(); e.Property(x => x.Notes).HasMaxLength(1000); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.CompletedBy).HasMaxLength(64); e.Property(x => x.CompletedByName).HasMaxLength(64); e.Property(x => x.CompletionComment).HasMaxLength(500); e.Property(x => x.CancelledBy).HasMaxLength(64); e.Property(x => x.CancelledByName).HasMaxLength(64); e.Property(x => x.CancellationReason).HasMaxLength(500); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.Number }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.UserId, x.Type, x.EffectiveDate }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.Status, x.EffectiveDate, x.UpdatedAt }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<PersonnelCaseTaskRecord>(e => { e.ToTable("personnel_case_task"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Code).HasMaxLength(64).IsRequired(); e.Property(x => x.Title).HasMaxLength(200).IsRequired(); e.Property(x => x.Category).HasMaxLength(32).IsRequired(); e.Property(x => x.AssigneeId).HasMaxLength(64).IsRequired(); e.Property(x => x.AssigneeName).HasMaxLength(64).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.Property(x => x.CompletionNote).HasMaxLength(500); e.Property(x => x.CompletedBy).HasMaxLength(64); e.Property(x => x.CompletedByName).HasMaxLength(64); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.PersonnelCaseId, x.Code }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.AssigneeId, x.Status, x.DueDate }); e.HasOne<PersonnelCaseRecord>().WithMany().HasForeignKey(x => x.PersonnelCaseId).OnDelete(DeleteBehavior.Cascade); });
        b.Entity<PersonnelCaseAlertDeliveryRecord>(e => { e.ToTable("personnel_case_alert_delivery"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.RecipientId).HasMaxLength(64).IsRequired(); e.Property(x => x.AlertType).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.PersonnelCaseTaskId, x.RecipientId, x.AlertType }).IsUnique().HasDatabaseName("UX_personnel_case_alert_delivery_task_recipient_type"); e.HasIndex(x => new { x.TenantId, x.DeliveredAt }); e.HasOne<PersonnelCaseTaskRecord>().WithMany().HasForeignKey(x => x.PersonnelCaseTaskId).OnDelete(DeleteBehavior.Cascade); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.RecipientId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<AttendanceShiftRecord>(e => { e.ToTable("attendance_shift"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Code).HasMaxLength(32).IsRequired(); e.Property(x => x.Name).HasMaxLength(100).IsRequired(); e.Property(x => x.UpdatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.Code }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.IsDefault, x.IsEnabled }); });
        b.Entity<AttendanceRecordEntity>(e => { e.ToTable("attendance_record"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.EmployeeName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentId).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(100).IsRequired(); e.Property(x => x.ShiftCode).HasMaxLength(32).IsRequired(); e.Property(x => x.ShiftName).HasMaxLength(100).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.Property(x => x.OriginalStatus).HasMaxLength(32); e.Property(x => x.Source).HasMaxLength(32).IsRequired(); e.Property(x => x.UpdatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.UserId, x.WorkDate }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.WorkDate, x.Status, x.UserId }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<AttendanceAppealRecord>(e => { e.ToTable("attendance_appeal"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired().IsConcurrencyToken(); e.Property(x => x.Reason).HasMaxLength(500).IsRequired(); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.SubmittedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.SubmittedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.ReviewedBy).HasMaxLength(64); e.Property(x => x.ReviewedByName).HasMaxLength(64); e.Property(x => x.ReviewComment).HasMaxLength(500); e.HasIndex(x => new { x.TenantId, x.Status, x.SubmittedAt }); e.HasIndex(x => x.AttendanceRecordId).IsUnique().HasFilter("\"Status\" = 'PENDING'").HasDatabaseName("UX_attendance_appeal_pending_record"); e.HasOne<AttendanceRecordEntity>().WithMany().HasForeignKey(x => x.AttendanceRecordId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<AttendanceMonthLockRecord>(e => { e.ToTable("attendance_month_lock"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.LockReason).HasMaxLength(500); e.Property(x => x.LockedBy).HasMaxLength(64); e.Property(x => x.LockedByName).HasMaxLength(64); e.Property(x => x.UnlockedBy).HasMaxLength(64); e.Property(x => x.UnlockedByName).HasMaxLength(64); e.Property(x => x.UnlockReason).HasMaxLength(500); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.Month }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.IsLocked, x.Month }); });
        b.Entity<AttendanceMonthSnapshotRecord>(e => { e.ToTable("attendance_month_snapshot"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.SnapshotJson).HasColumnType("text").IsRequired(); e.Property(x => x.SnapshotHash).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.CreatedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.LockReason).HasMaxLength(500).IsRequired(); e.HasIndex(x => new { x.TenantId, x.Month, x.Sequence }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.Month, x.CreatedAt }); });
        b.Entity<EmploymentContractRecord>(e => { e.ToTable("employment_contract"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.ContractNumber).HasMaxLength(32).IsRequired(); e.Property(x => x.UserId).HasMaxLength(64).IsRequired(); e.Property(x => x.EmployeeName).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentId).HasMaxLength(64).IsRequired(); e.Property(x => x.DepartmentName).HasMaxLength(100).IsRequired(); e.Property(x => x.PositionName).HasMaxLength(100).IsRequired(); e.Property(x => x.WorkLocation).HasMaxLength(100).IsRequired(); e.Property(x => x.ContractType).HasMaxLength(32).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.Property(x => x.ProjectDescription).HasMaxLength(500); e.Property(x => x.AttachmentsJson).HasColumnType("jsonb"); e.Property(x => x.Notes).HasMaxLength(1000); e.Property(x => x.OpenEndedReviewReason).HasMaxLength(500); e.Property(x => x.TerminationReason).HasMaxLength(500); e.Property(x => x.CreatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.UpdatedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.Version).IsConcurrencyToken(); e.HasIndex(x => new { x.TenantId, x.ContractNumber }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.UserId, x.Status, x.EndDate }); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Restrict); e.HasOne<EmploymentContractRecord>().WithMany().HasForeignKey(x => x.RenewalOfId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<EmploymentContractEventRecord>(e => { e.ToTable("employment_contract_event"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.EventType).HasMaxLength(32).IsRequired(); e.Property(x => x.Summary).HasMaxLength(500).IsRequired(); e.Property(x => x.Reason).HasMaxLength(500).IsRequired(); e.Property(x => x.ChangedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.ChangedByName).HasMaxLength(64).IsRequired(); e.Property(x => x.SnapshotJson).HasColumnType("jsonb"); e.HasIndex(x => new { x.TenantId, x.ContractId, x.CreatedAt }); e.HasOne<EmploymentContractRecord>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<ContractAlertAcknowledgementRecord>(e => { e.ToTable("contract_alert_ack"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.AcknowledgedBy).HasMaxLength(64).IsRequired(); e.Property(x => x.AcknowledgedByName).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.ContractId, x.ThresholdDays }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.AcknowledgedAt }); e.HasOne<EmploymentContractRecord>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); });
        b.Entity<ContractAlertDeliveryRecord>(e => { e.ToTable("contract_alert_delivery"); e.HasKey(x => x.Id); e.Property(x => x.TenantId).HasMaxLength(64).IsRequired(); e.Property(x => x.RecipientId).HasMaxLength(64).IsRequired(); e.HasIndex(x => new { x.ContractId, x.RecipientId, x.ThresholdDays }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.DeliveredAt }); e.HasOne<EmploymentContractRecord>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); e.HasOne<UserRecord>().WithMany().HasForeignKey(x => x.RecipientId).OnDelete(DeleteBehavior.Restrict); });
    }
}

public sealed class LeaveRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public int Type { get; set; } public DateOnly StartDate { get; set; } public int StartPeriod { get; set; } public DateOnly EndDate { get; set; } public int EndPeriod { get; set; } public decimal Days { get; set; } public string Reason { get; set; } = string.Empty; public string AttachmentsJson { get; set; } = "[]"; public int Status { get; set; } public int Version { get; set; } = 1; public Guid? ProcessDefinitionId { get; set; } public string? ProcessDefinitionCode { get; set; } public int? ProcessDefinitionVersion { get; set; } public Guid? CurrentFlowInstanceId { get; set; } public int? BalanceYear { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class FlowTaskRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public Guid LeaveRequestId { get; set; } public Guid? FlowInstanceId { get; set; } public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public string? OriginalAssigneeId { get; set; } public string? OriginalAssigneeName { get; set; } public Guid? DelegationId { get; set; } public int Sequence { get; set; } public int Status { get; set; } public string? Comment { get; set; } public DateTimeOffset? ProcessedAt { get; set; } }
public sealed class LeaveBalanceRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string UserId { get; set; } = string.Empty; public int LeaveType { get; set; } public int Year { get; set; } public decimal StatutoryEntitled { get; set; } public decimal Adjustment { get; set; } public decimal Entitled { get; set; } public decimal Frozen { get; set; } public decimal Used { get; set; } public int Version { get; set; } = 1; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ExpenseRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public Guid? TravelRequestId { get; set; } public string? Project { get; set; } public string PayeeAccountName { get; set; } = string.Empty; public string PayeeAccount { get; set; } = string.Empty; public string? BankName { get; set; } public string? Description { get; set; } public decimal TotalAmount { get; set; } public int Status { get; set; } public int Version { get; set; } = 1; public Guid? ProcessDefinitionId { get; set; } public string? ProcessDefinitionCode { get; set; } public int? ProcessDefinitionVersion { get; set; } public Guid? CurrentFlowInstanceId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ExpenseItemRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ExpenseClaimId { get; set; } public DateOnly ExpenseDate { get; set; } public string Category { get; set; } = string.Empty; public decimal Amount { get; set; } public string Description { get; set; } = string.Empty; public string? ReceiptNumber { get; set; } public string AttachmentsJson { get; set; } = "[]"; }
public sealed class ExpenseTaskRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public Guid ExpenseClaimId { get; set; } public Guid? FlowInstanceId { get; set; } public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public string? OriginalAssigneeId { get; set; } public string? OriginalAssigneeName { get; set; } public Guid? DelegationId { get; set; } public int Sequence { get; set; } public int Status { get; set; } public string? Comment { get; set; } public DateTimeOffset? ProcessedAt { get; set; } }
public sealed class TravelRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public string Purpose { get; set; } = string.Empty; public DateOnly StartDate { get; set; } public DateOnly EndDate { get; set; } public int Days { get; set; } public decimal EstimatedBudget { get; set; } public string ItineraryJson { get; set; } = "[]"; public string CompanionIdsJson { get; set; } = "[]"; public string AttachmentsJson { get; set; } = "[]"; public int Status { get; set; } public int Version { get; set; } = 1; public Guid? ProcessDefinitionId { get; set; } public string? ProcessDefinitionCode { get; set; } public int? ProcessDefinitionVersion { get; set; } public Guid? CurrentFlowInstanceId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class TravelTaskRecord { public Guid Id { get; set; } public string TenantId { get; set; } = "demo"; public Guid TravelRequestId { get; set; } public Guid? FlowInstanceId { get; set; } public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public string? OriginalAssigneeId { get; set; } public string? OriginalAssigneeName { get; set; } public Guid? DelegationId { get; set; } public int Sequence { get; set; } public int Status { get; set; } public string? Comment { get; set; } public DateTimeOffset? ProcessedAt { get; set; } }
public sealed class PurchaseRequestRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Purpose { get; set; } = string.Empty; public DateOnly RequiredDate { get; set; } public string? SuggestedSupplier { get; set; } public string ItemsJson { get; set; } = "[]"; public string ItemSearchText { get; set; } = string.Empty; public int ItemCount { get; set; } public decimal EstimatedTotal { get; set; } public string AttachmentsJson { get; set; } = "[]"; public int Status { get; set; } public int Version { get; set; } = 1; public bool IsDemo { get; set; } public Guid? ProcessDefinitionId { get; set; } public string? ProcessDefinitionCode { get; set; } public int? ProcessDefinitionVersion { get; set; } public Guid? CurrentFlowInstanceId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PurchaseTaskRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid PurchaseRequestId { get; set; } public Guid? FlowInstanceId { get; set; } public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public string? OriginalAssigneeId { get; set; } public string? OriginalAssigneeName { get; set; } public Guid? DelegationId { get; set; } public int Sequence { get; set; } public int Status { get; set; } public string? Comment { get; set; } public DateTimeOffset? ProcessedAt { get; set; } public int Version { get; set; } = 1; }
public sealed class PurchaseOrderRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid PurchaseRequestId { get; set; } public string Supplier { get; set; } = string.Empty; public string OrderNumber { get; set; } = string.Empty; public decimal ActualAmount { get; set; } public DateOnly OrderDate { get; set; } public DateOnly ExpectedDeliveryDate { get; set; } public string? Notes { get; set; } public string AttachmentsJson { get; set; } = "[]"; public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PurchaseReceiptRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid PurchaseRequestId { get; set; } public DateOnly ReceivedDate { get; set; } public string Result { get; set; } = "ALL_ACCEPTED"; public string Notes { get; set; } = string.Empty; public string AttachmentsJson { get; set; } = "[]"; public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class SealRequestRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string DocumentCategory { get; set; } = string.Empty; public string DocumentName { get; set; } = string.Empty; public string SealType { get; set; } = string.Empty; public int Copies { get; set; } public bool IsOut { get; set; } public DateOnly? OutStartDate { get; set; } public DateOnly? OutEndDate { get; set; } public string? OutCustodian { get; set; } public string Reason { get; set; } = string.Empty; public string AttachmentsJson { get; set; } = "[]"; public int Status { get; set; } public int Version { get; set; } = 1; public bool IsDemo { get; set; } public Guid? ProcessDefinitionId { get; set; } public string? ProcessDefinitionCode { get; set; } public int? ProcessDefinitionVersion { get; set; } public Guid? CurrentFlowInstanceId { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class SealTaskRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid SealRequestId { get; set; } public Guid? FlowInstanceId { get; set; } public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public string? OriginalAssigneeId { get; set; } public string? OriginalAssigneeName { get; set; } public Guid? DelegationId { get; set; } public int Sequence { get; set; } public int Status { get; set; } public string? Comment { get; set; } public DateTimeOffset? ProcessedAt { get; set; } public int Version { get; set; } = 1; }
public sealed class SealExecutionRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid SealRequestId { get; set; } public DateOnly ExecutedDate { get; set; } public string OperatorName { get; set; } = string.Empty; public string? Notes { get; set; } public string AttachmentsJson { get; set; } = "[]"; public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class SealReturnRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid SealRequestId { get; set; } public DateOnly ReturnDate { get; set; } public string SealCondition { get; set; } = "INTACT"; public string ReceiverName { get; set; } = string.Empty; public string? Notes { get; set; } public string AttachmentsJson { get; set; } = "[]"; public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PaymentRecordEntity { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ExpenseClaimId { get; set; } public DateOnly PaymentDate { get; set; } public string PaymentMethod { get; set; } = string.Empty; public string TransactionNumber { get; set; } = string.Empty; public decimal PaidAmount { get; set; } public string ProofFile { get; set; } = string.Empty; public string OperatorId { get; set; } = string.Empty; }
public sealed class AuditRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string ActorId { get; set; } = string.Empty; public string Action { get; set; } = string.Empty; public string ResourceType { get; set; } = string.Empty; public string ResourceId { get; set; } = string.Empty; public string Summary { get; set; } = string.Empty; public DateTimeOffset OccurredAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class IdempotencyRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string ActorId { get; set; } = string.Empty; public string Route { get; set; } = string.Empty; public string Key { get; set; } = string.Empty; public string? RequestHash { get; set; } public int StatusCode { get; set; } public string ResponseJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class WorkCalendarRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public DateOnly Date { get; set; } public bool IsWorkingDay { get; set; } public string? Note { get; set; } public string UpdatedBy { get; set; } = string.Empty; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class NotificationRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string RecipientId { get; set; } = string.Empty; public string Type { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public string ResourceType { get; set; } = string.Empty; public string ResourceId { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? ReadAt { get; set; } }
public sealed class FileRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string OwnerId { get; set; } = string.Empty; public string OriginalName { get; set; } = string.Empty; public string StoredName { get; set; } = string.Empty; public string ContentType { get; set; } = string.Empty; public long Size { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ProcessDefinitionRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public string BusinessType { get; set; } = string.Empty; public int Version { get; set; } = 1; public int Status { get; set; } public int Priority { get; set; } public string CreatedBy { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public string? PublishedBy { get; set; } public DateTimeOffset? PublishedAt { get; set; } }
public sealed class ProcessRuleRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProcessDefinitionId { get; set; } public int Sequence { get; set; } public decimal? MaxValue { get; set; } }
public sealed class ProcessNodeRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProcessRuleId { get; set; } public int Sequence { get; set; } public string AssigneeKey { get; set; } = string.Empty; }
public sealed class ProcessScopeRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProcessDefinitionId { get; set; } public string ScopeType { get; set; } = string.Empty; public string Value { get; set; } = string.Empty; }
public sealed class FlowDelegationRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string OwnerId { get; set; } = string.Empty; public string DelegateId { get; set; } = string.Empty; public string BusinessType { get; set; } = "All"; public DateTimeOffset StartAt { get; set; } public DateTimeOffset EndAt { get; set; } public string Reason { get; set; } = string.Empty; public int Status { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? CancelledAt { get; set; } }
public sealed class FlowInstanceRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string BusinessType { get; set; } = string.Empty; public Guid BusinessId { get; set; } public string BusinessNumber { get; set; } = string.Empty; public string ApplicantId { get; set; } = string.Empty; public Guid ProcessDefinitionId { get; set; } public string ProcessDefinitionCode { get; set; } = string.Empty; public int ProcessDefinitionVersion { get; set; } public int Attempt { get; set; } public int Status { get; set; } public DateTimeOffset StartedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? CompletedAt { get; set; } }
public sealed class FlowActionRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid FlowInstanceId { get; set; } public Guid? TaskId { get; set; } public int? Sequence { get; set; } public int Action { get; set; } public string ActorId { get; set; } = string.Empty; public string ActorName { get; set; } = string.Empty; public string? FromAssigneeId { get; set; } public string? FromAssigneeName { get; set; } public string? ToAssigneeId { get; set; } public string? ToAssigneeName { get; set; } public string? Comment { get; set; } public DateTimeOffset OccurredAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class FlowCopyRecipientRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string BusinessType { get; set; } = string.Empty; public Guid BusinessId { get; set; } public string BusinessNumber { get; set; } = string.Empty; public string ApplicantName { get; set; } = string.Empty; public string RecipientId { get; set; } = string.Empty; public string RecipientName { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Status { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? AvailableAt { get; set; } public DateTimeOffset? ReadAt { get; set; } }
public sealed class DepartmentRecord { public string Id { get; set; } = string.Empty; public string TenantId { get; set; } = "demo"; public string Name { get; set; } = string.Empty; public string? ParentId { get; set; } public int SortOrder { get; set; } public bool IsSystem { get; set; } public int Version { get; set; } = 1; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PositionRecord { public string Id { get; set; } = string.Empty; public string TenantId { get; set; } = "demo"; public string Name { get; set; } = string.Empty; public string DepartmentId { get; set; } = string.Empty; public int SortOrder { get; set; } public string Status { get; set; } = "ACTIVE"; public bool IsSystem { get; set; } public int Version { get; set; } = 1; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class UserRecord { public string Id { get; set; } = string.Empty; public string TenantId { get; set; } = "demo"; public string Name { get; set; } = string.Empty; public string DepartmentId { get; set; } = string.Empty; public string? PositionId { get; set; } public string? ManagerId { get; set; } public int CumulativeWorkYears { get; set; } public string Status { get; set; } = "ACTIVE"; public int Version { get; set; } = 1; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class UserAccountRecord { public string UserId { get; set; } = string.Empty; public string PasswordSalt { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; public int PasswordIterations { get; set; } = 120_000; public int FailedLoginCount { get; set; } public DateTimeOffset? LockedUntil { get; set; } public DateTimeOffset PasswordChangedAt { get; set; } = DateTimeOffset.UtcNow; public bool MustChangePassword { get; set; } public bool MfaEnabled { get; set; } public string? MfaSecretCiphertext { get; set; } public string RecoveryCodeHashesJson { get; set; } = "[]"; public long? LastTotpTimeStep { get; set; } public DateTimeOffset? MfaEnabledAt { get; set; } public DateTimeOffset? MfaUpdatedAt { get; set; } }
public sealed class RoleRecord { public string Code { get; set; } = string.Empty; public string TenantId { get; set; } = "demo"; public string Name { get; set; } = string.Empty; public bool IsSystem { get; set; } = true; }
public sealed class UserRoleRecord { public string UserId { get; set; } = string.Empty; public string RoleCode { get; set; } = string.Empty; public bool IsPrimary { get; set; } }
public sealed class RolePermissionRecord { public string RoleCode { get; set; } = string.Empty; public string PermissionCode { get; set; } = string.Empty; }
public sealed class RoleDataScopeRecord { public string RoleCode { get; set; } = string.Empty; public string ResourceType { get; set; } = string.Empty; public string Scope { get; set; } = "SELF"; }
public sealed class AuthSessionRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string UserId { get; set; } = string.Empty; public string RefreshTokenHash { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset LastUsedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? RevokedAt { get; set; } public string? RevokedReason { get; set; } public string? UserAgent { get; set; } public string? IpAddress { get; set; } }
public sealed class MfaChallengeRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string UserId { get; set; } = string.Empty; public string TokenHash { get; set; } = string.Empty; public string Purpose { get; set; } = "VERIFY"; public string? PendingSecretCiphertext { get; set; } public int FailedAttempts { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? ConsumedAt { get; set; } public string? UserAgent { get; set; } public string? IpAddress { get; set; } }
public sealed class AnnouncementRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Title { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public string Status { get; set; } = "DRAFT"; public int Version { get; set; } = 1; public string CreatedBy { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public string? PublishedBy { get; set; } public DateTimeOffset? PublishedAt { get; set; } public string? WithdrawnBy { get; set; } public DateTimeOffset? WithdrawnAt { get; set; } public DateTimeOffset? ExpiresAt { get; set; } }
public sealed class AnnouncementReadRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid AnnouncementId { get; set; } public string UserId { get; set; } = string.Empty; public DateTimeOffset ReadAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PersonnelProfileRecord { public string UserId { get; set; } = string.Empty; public string TenantId { get; set; } = "demo"; public string EmployeeNumber { get; set; } = string.Empty; public string WorkEmail { get; set; } = string.Empty; public string WorkPhone { get; set; } = string.Empty; public string WorkLocation { get; set; } = string.Empty; public string EmploymentType { get; set; } = "FULL_TIME"; public string PersonnelStatus { get; set; } = "ACTIVE"; public DateOnly HireDate { get; set; } public DateOnly? ProbationEndDate { get; set; } public DateOnly? RegularizedDate { get; set; } public DateOnly? CumulativeWorkStartDate { get; set; } public DateOnly? DepartureDate { get; set; } public string? DepartureReason { get; set; } public int Version { get; set; } = 1; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PersonnelEventRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string UserId { get; set; } = string.Empty; public string EventType { get; set; } = string.Empty; public DateOnly EffectiveDate { get; set; } public string Summary { get; set; } = string.Empty; public string ChangedBy { get; set; } = string.Empty; public string ChangedByName { get; set; } = string.Empty; public string SnapshotJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PersonnelCaseRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Number { get; set; } = string.Empty; public string UserId { get; set; } = string.Empty; public string EmployeeName { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public string Type { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public DateOnly EffectiveDate { get; set; } public string Status { get; set; } = "OPEN"; public string OwnerId { get; set; } = string.Empty; public string OwnerName { get; set; } = string.Empty; public string? Notes { get; set; } public int Version { get; set; } = 1; public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public string? CompletedBy { get; set; } public string? CompletedByName { get; set; } public DateTimeOffset? CompletedAt { get; set; } public string? CompletionComment { get; set; } public string? CancelledBy { get; set; } public string? CancelledByName { get; set; } public DateTimeOffset? CancelledAt { get; set; } public string? CancellationReason { get; set; } }
public sealed class PersonnelCaseTaskRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid PersonnelCaseId { get; set; } public string Code { get; set; } = string.Empty; public string Title { get; set; } = string.Empty; public string Category { get; set; } = string.Empty; public bool Required { get; set; } = true; public string AssigneeId { get; set; } = string.Empty; public string AssigneeName { get; set; } = string.Empty; public DateOnly DueDate { get; set; } public string Status { get; set; } = "PENDING"; public string? CompletionNote { get; set; } public string? CompletedBy { get; set; } public string? CompletedByName { get; set; } public DateTimeOffset? CompletedAt { get; set; } public int SortOrder { get; set; } public int Version { get; set; } = 1; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class PersonnelCaseAlertDeliveryRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid PersonnelCaseTaskId { get; set; } public string RecipientId { get; set; } = string.Empty; public string AlertType { get; set; } = string.Empty; public DateTimeOffset DeliveredAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class AttendanceShiftRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public TimeOnly WorkStart { get; set; } public TimeOnly WorkEnd { get; set; } public int BreakMinutes { get; set; } public int LateToleranceMinutes { get; set; } public int EarlyLeaveToleranceMinutes { get; set; } public bool IsDefault { get; set; } public bool IsEnabled { get; set; } = true; public int Version { get; set; } = 1; public string UpdatedBy { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class AttendanceRecordEntity { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string UserId { get; set; } = string.Empty; public string EmployeeName { get; set; } = string.Empty; public string DepartmentId { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public DateOnly WorkDate { get; set; } public string ShiftCode { get; set; } = string.Empty; public string ShiftName { get; set; } = string.Empty; public TimeOnly ScheduledStart { get; set; } public TimeOnly ScheduledEnd { get; set; } public DateTimeOffset? CheckInAt { get; set; } public DateTimeOffset? CheckOutAt { get; set; } public string Status { get; set; } = "NORMAL"; public string? OriginalStatus { get; set; } public int WorkedMinutes { get; set; } public int LateMinutes { get; set; } public int EarlyLeaveMinutes { get; set; } public string Source { get; set; } = "IMPORT"; public int Version { get; set; } = 1; public string UpdatedBy { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class AttendanceAppealRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid AttendanceRecordId { get; set; } public string Status { get; set; } = "PENDING"; public string Reason { get; set; } = string.Empty; public string AttachmentsJson { get; set; } = "[]"; public string SubmittedBy { get; set; } = string.Empty; public string SubmittedByName { get; set; } = string.Empty; public DateTimeOffset SubmittedAt { get; set; } = DateTimeOffset.UtcNow; public string? ReviewedBy { get; set; } public string? ReviewedByName { get; set; } public string? ReviewComment { get; set; } public DateTimeOffset? ReviewedAt { get; set; } }
public sealed class AttendanceMonthLockRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public DateOnly Month { get; set; } public bool IsLocked { get; set; } public int Version { get; set; } = 1; public string? LockReason { get; set; } public string? LockedBy { get; set; } public string? LockedByName { get; set; } public DateTimeOffset? LockedAt { get; set; } public string? UnlockedBy { get; set; } public string? UnlockedByName { get; set; } public DateTimeOffset? UnlockedAt { get; set; } public string? UnlockReason { get; set; } public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class AttendanceMonthSnapshotRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public DateOnly Month { get; set; } public int Sequence { get; set; } public string SnapshotJson { get; set; } = "[]"; public string SnapshotHash { get; set; } = string.Empty; public int RowCount { get; set; } public string CreatedBy { get; set; } = string.Empty; public string CreatedByName { get; set; } = string.Empty; public string LockReason { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class EmploymentContractRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public string ContractNumber { get; set; } = string.Empty; public string UserId { get; set; } = string.Empty; public string EmployeeName { get; set; } = string.Empty; public string DepartmentId { get; set; } = string.Empty; public string DepartmentName { get; set; } = string.Empty; public string PositionName { get; set; } = string.Empty; public string WorkLocation { get; set; } = string.Empty; public string ContractType { get; set; } = "FIXED_TERM"; public string Status { get; set; } = "DRAFT"; public DateOnly? SignedDate { get; set; } public DateOnly StartDate { get; set; } public DateOnly? EndDate { get; set; } public DateOnly? ProbationStartDate { get; set; } public DateOnly? ProbationEndDate { get; set; } public string? ProjectDescription { get; set; } public string AttachmentsJson { get; set; } = "[]"; public string? Notes { get; set; } public Guid? RenewalOfId { get; set; } public int RenewalSequence { get; set; } public bool OpenEndedReviewRequired { get; set; } public string? OpenEndedReviewReason { get; set; } public DateOnly? TerminationDate { get; set; } public string? TerminationReason { get; set; } public bool IsDemo { get; set; } public int Version { get; set; } = 1; public string CreatedBy { get; set; } = string.Empty; public string UpdatedBy { get; set; } = string.Empty; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class EmploymentContractEventRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid ContractId { get; set; } public string EventType { get; set; } = string.Empty; public string Summary { get; set; } = string.Empty; public string Reason { get; set; } = string.Empty; public string ChangedBy { get; set; } = string.Empty; public string ChangedByName { get; set; } = string.Empty; public string SnapshotJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ContractAlertAcknowledgementRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid ContractId { get; set; } public int ThresholdDays { get; set; } public string AcknowledgedBy { get; set; } = string.Empty; public string AcknowledgedByName { get; set; } = string.Empty; public DateTimeOffset AcknowledgedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class ContractAlertDeliveryRecord { public Guid Id { get; set; } = Guid.NewGuid(); public string TenantId { get; set; } = "demo"; public Guid ContractId { get; set; } public string RecipientId { get; set; } = string.Empty; public int ThresholdDays { get; set; } public DateTimeOffset DeliveredAt { get; set; } = DateTimeOffset.UtcNow; }
